In [8]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
f = open('iris.txt')
data = []
y=[]
for i in f.read().split():
    data.append([float(j)for j in i.split(',')[:-1]])
    y.append(i.split(',')[-1])
    
data = np.array(data) # 原始数据
n = data.shape[0] # 样本个数
m = data.shape[1] # 样本维数

## 2.1 计算中心化标准化后的数据的和矩阵

In [10]:
km1 = np.zeros([n,n])
for i in range(n):
    for j in range(n):
        km1[i][j] = data[i].dot(data[j])**2
km1

array([[ 4057.69  ,  5305.6656,  4748.5881, ...,  5449.3924,  7791.5929,
         2198.6721],
       [ 5305.6656,  6968.9104,  6244.1604, ...,  7133.4916, 10209.0816,
         2849.4244],
       [ 4748.5881,  6244.1604,  5598.0324, ...,  6372.8289,  9124.0704,
         2568.4624],
       ...,
       [ 5449.3924,  7133.4916,  6372.8289, ...,  7433.8884, 10586.3521,
         2769.9169],
       [ 7791.5929, 10209.0816,  9124.0704, ..., 10586.3521, 15242.3716,
         3928.7824],
       [ 2198.6721,  2849.4244,  2568.4624, ...,  2769.9169,  3928.7824,
         1588.8196]])

In [13]:
mean = np.mean(km1,axis=0)
km1 = km1 - np.ones([n,1])*mean

for i in range(n):
    km1[:,i] = (km1[:,i] - np.min(km1[:,i])) /(np.max(km1[:,i])-np.min(km1[:,i]))
km1

array([[0.40349685, 0.40405313, 0.40366731, ..., 0.40759841, 0.40526808,
        0.38485212],
       [0.60286502, 0.60619905, 0.60749824, ..., 0.60181116, 0.59823552,
        0.60763806],
       [0.51387007, 0.51811505, 0.51943772, ..., 0.51409044, 0.51162836,
        0.51145033],
       ...,
       [0.62582584, 0.62620177, 0.62503442, ..., 0.63645335, 0.62834979,
        0.58041856],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        0.97715774],
       [0.10651269, 0.10552874, 0.10653887, ..., 0.09859744, 0.09693296,
        0.17606829]])

## 2.2 再进行中心化和标准化

In [15]:
s1 = np.zeros([n,10])
a = 2.0**0.5
for i in range(n):
    s1[i] = np.array([data[i][0]**2,data[i][1]**2,data[i][2]**2,data[i][3]**2,
                       a*data[i][0]*data[i][1],a*data[i][1]*data[i][2],a*data[i][2]*data[i][3],
                       a*data[i][0]*data[i][2],a*data[i][1]*data[i][3],a*data[i][0]*data[i][3]])
s1

array([[34.81      ,  9.        , 17.64      , ..., 35.04421208,
         6.36396103, 12.51579003],
       [47.61      ,  9.61      , 24.01      , ..., 47.81456054,
         6.57609307, 14.63711037],
       [43.56      ,  8.41      , 21.16      , ..., 42.93552375,
         5.33158513, 12.13395237],
       ...,
       [44.89      ,  9.        , 27.04      , ..., 49.27120051,
         9.75807358, 21.793031  ],
       [59.29      , 14.44      , 44.89      , ..., 72.95927768,
        11.82282538, 23.95677775],
       [26.01      , 11.56      ,  2.25      , ..., 10.81873375,
         0.96166522,  1.44249783]])

In [16]:
km2 = np.zeros([n,n])
for i in range(n):
    for j in range(n):
        km2[i][j] = s1[i].dot(s1[j])
km2

array([[ 4057.69  ,  5305.6656,  4748.5881, ...,  5449.3924,  7791.5929,
         2198.6721],
       [ 5305.6656,  6968.9104,  6244.1604, ...,  7133.4916, 10209.0816,
         2849.4244],
       [ 4748.5881,  6244.1604,  5598.0324, ...,  6372.8289,  9124.0704,
         2568.4624],
       ...,
       [ 5449.3924,  7133.4916,  6372.8289, ...,  7433.8884, 10586.3521,
         2769.9169],
       [ 7791.5929, 10209.0816,  9124.0704, ..., 10586.3521, 15242.3716,
         3928.7824],
       [ 2198.6721,  2849.4244,  2568.4624, ...,  2769.9169,  3928.7824,
         1588.8196]])

In [17]:
mean2 = np.mean(km2,axis=0)
z2 = km2 - np.ones([n,1])*mean2
for i in range(n):
    z2[:,i] = (z2[:,i] - np.min(z2[:,i])) /(np.max(z2[:,i])-np.min(z2[:,i]))
z2

array([[0.40349685, 0.40405313, 0.40366731, ..., 0.40759841, 0.40526808,
        0.38485212],
       [0.60286502, 0.60619905, 0.60749824, ..., 0.60181116, 0.59823552,
        0.60763806],
       [0.51387007, 0.51811505, 0.51943772, ..., 0.51409044, 0.51162836,
        0.51145033],
       ...,
       [0.62582584, 0.62620177, 0.62503442, ..., 0.63645335, 0.62834979,
        0.58041856],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        0.97715774],
       [0.10651269, 0.10552874, 0.10653887, ..., 0.09859744, 0.09693296,
        0.17606829]])